### ISSUE TITLE
Add `dataset` extractor for `Meeseeks.Result`

### ISSUE THREAD

**Issue by mischov** [mischov/meeseeks#1]
Add function `Meeseeks.Result.dataset` (and `Meeseeks.dataset`) inspired by [HTMLElement.dataset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset).

```elixir
iex> import Meeseeks.CSS
...
iex> html = "<div class=\"user\" data-id=\"123\" data-first-name=\"Hans\">Hans</div>"
...
iex> result = Meeseeks.all(html, css(".user"))
...
iex> Meeseeks.dataset(result)
%{"id" => "123", "first-name" => "Hans"} 
```
The suggestion was made by @Eiji7 for `dataset` to support value casting (ie, converting the above value of `"id"` from `"123"` to `123`), but I think that this is beyond the scope of the library.

### Implementation:

If one were to stick closely to the name mangling of HTMLElement.dataset, instead of creating:

```elixir
 %{"id" => "123", "first-name" => "Hans"}
```
we would create:

```elixir
%{"id" => "123", "firstName" => "Hans"}
```
or, if we were to stick to Elixir naming convention:
```elixir
%{"id" => "123", "first_name" => "Hans"} 
```

Just sticking with dash (`-`) would require the least string manipulation, and is my preferred choice, but I am willing to be convinced otherwise.

**Comment by Eiji7** [comment]
@mischov:
> The suggestion was made by @Eiji7 for dataset to support value casting (ie, converting the above value of "id" from "123" to 123), but I think that this is beyond the scope of the library.

So if we are not going to implement our methods (for atoms like :integer) then how about just allow to add own methods like:
```elixir
Meeseeks.dataset(result, cast: %{"id" => &String.to_integer/1})
```
I'm working on scraping project and I see that auto casting would be really helpful.

> or, if we were to stick to Elixir naming convention:

If so then how about convert it to `Atom`, so we can simple fetch them like:
```elixir
Meeseeks.dataset(result).id
```

**Comment by mischov** [comment]
@Eiji7 
> I'm working on scraping project and I see that auto casting would be really helpful in my case.
So if we are not going to implement our methods (for atoms like :integer) then how about just allow to add own methods:

Is there any benefit to combining dataset extraction and casting other than saving a little iteration?

```elixir
Meeseeks.dataset(result)
|> cast(%{"id" => &String.to_integer/1})
```

> If so then how about convert it to Atom, so we can simple fetch them

No go on that one- Atoms are not garbage collected so converting arbitrary/outside data from Strings to Atoms is generally not done.

**Comment by Eiji7** [comment]
@mischov:
> Is there any benefit to combining dataset extraction and casting other than saving a little iteration?

ok, now I have a better plan for it (I can simply use Ecto for casting), nvm

**Comment by mischov** [comment]
@Eiji7 
> I can simply use Ecto for casting
Yeah, that was one reason I was suggesting to keep it separate.

No preference on whether I mangle the dataset key names (`"data-first-name"` to `"first-name"` or `"firstName"`)?

**Comment by Eiji7** [comment]
@mischov: `dataset` method should not return `data-` part.
I think that you have 2 choices to decide about it to keep it simple to understand:

1. **as a CSS/HTML developer/designer** the simplest way is just: `first-name`
2. however any **JavaScript developer** (probably most of developers) would prefer `firstName`

I think that you should choose a **JavaScript developer** way, because developers looking for **similar feature** already know about original implementation and for other developers it will remain a curiosity.

**Comment by mischov** [comment]
@Eiji7 
I agree. 

Because the `dataset` is inspired by `HTMLElement.dataset`, I will keep name-mangling consistent with what users of `HTMLElement.dataset` expect.

Thank you for your feedback, I will move on to adding the feature now.
