### ISSUE TITLE
Can't fetch the data successfully from the document

### ISSUE THREAD

**Issue by dbesserman** [mischov/meeseeks#101]
I'm trying to fetch data from a page.The parsing of the document works fine. But when I want to fetch the actual data from the document with `Meeseeks.one`, it returns nil as if there were no matching result for the selector.

The body of the response contains:
```html
               <noscript>
                                                                            <p class=" item-price-noreduc item-price"
                          content="42,2" >
                       42,20 €                   </p>
               </noscript>
```
I then parse the body of the response and try to get the data contained in the <p> tag.

```
iex(1)> document = Meeseeks.parse(body)
#Meeseeks.Document<{...}>
iex(2)> Meeseeks.one(document, css(".item-price"))
nil
```
Any idea why this is happening? 
Thanks

**Comment by mischov** [comment]
An HTML5 parser that behaves as if scripting is enabled (which is the assumption `html5ever` makes by default) reads the contents of a noscript tag as text (see [the HTML5 spec](https://www.w3.org/TR/html52/semantics-scripting.html#the-noscript-element) for details).

There is no element with the class `.item-price` in the document because the parsed contents of the noscript tag is the text

```
"\n                                                                            <p class=\" item-price-noreduc item-price\"\n                          content=\"42,2\" >\n                       42,20 €                   </p>\n               "
```

**Comment by dbesserman** [comment]
Ok, so I need to remove the <noscript> tags from the body of the response before Meeseeks parses it. Thanks!

**Comment by mischov** [comment]
Yeah, something like that would be the fastest solution. Here's an example of one way a person could go about this.

```elixir
parsed
|> Meeseeks.one(css("noscript")) 
|> Meeseeks.text() 
|> Meeseeks.parse() 
|> Meeseeks.one(css(".item-price"))
```

Another solution would be to allow the parser to be passed an option that says scripting is disabled, but I don't support that yet.
