### ISSUE TITLE
Issue even when input is a valid utf8

### ISSUE THREAD

**Issue by sreecodeslayer** [mischov/meeseeks#108]
We use Meeseeks in a website crawler which simply gets the whole text from the home page of websites.
I have been noticing the "input is not valid utf8" error
```elixir
iex> Meeseeks.parse(html_text)
{:error, %Meeseeks.Error{
  metadata: %{
    description: "input is not valid utf8",
    input: "<redacted>"
  },
  reason: :invalid_input,
  type: :parser
}}
```
come up more often, but has been bugging us lately a lot more.

Here is the sample website: https://cpnsku.id/ : html dump: [meeseeks-utf8-check.txt](https://github.com/mischov/meeseeks/files/6536627/meeseeks-utf8-check.txt)

I checked the html text against some utf8 validators online, and none of them showed any red flag. Any idea what exactly is happening here?

[edit:  adding thread panic traceback from rust]
```
thread '<unnamed>' panicked at 'input is not valid utf8', src/lib.rs:144:31
stack backtrace:
0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
1: core::fmt::write
2: std::io::Write::write_fmt
3: std::panicking::default_hook::{{closure}}
4: std::panicking::default_hook
5: std::panicking::rust_panic_with_hook
6: std::panicking::begin_panic
7: meeseeks_html5ever_nif::parse::{{closure}}
8: meeseeks_html5ever_nif::parse
9: std::panicking::try
10: meeseeks_html5ever_nif::nif_init::FUN_ENTRIES::nif_func
11: erts_call_dirty_nif
12: erts_dirty_process_main
13: sched_dirty_cpu_thread_func
14: thr_wrapper
15: _pthread_start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sreecodeslayer** [comment]
Found out that some of the websites are using `latin1` or `cp1252` encoding.

Using [:iconv](https://github.com/processone/iconv) and [:zlib](https://erlang.org/doc/man/zlib.html#gunzip-1), converted the gzipped response body to utf8 and things looks good.

**Comment by mischov** [comment]
I'm glad you were able to figure it out, and thank you for creating the issue since it provides good documentation for others with the same issue.
