### ISSUE TITLE
Parsing a table?

### ISSUE THREAD

**Issue by madasebrof** [mischov/meeseeks#14]
I'm trying to get data from this website:

http://financials.morningstar.com/fund/expense.html?t=FINPX

Specifically, I am looking for something in a table. I can get the `id`, but nothing below it.

Xpath (from Chrome):

`//*[@id="otherFeesExpensesHtml"]/table/tbody/tr[1]/td`

CSS (from Chrome):
`#otherFeesExpensesHtml > table > tbody > tr:nth-child(1) > td`

Is this not supported?

Thanks!

**Comment by mischov** [comment]
When fetching that site's html with HTTPoison, I'm seeing that the `#otherFeesExpensesHtml` is an empty div `<div id=\"otherFeesExpensesHtml\"></div>\n` and that there seems to be a script to later fill in that data:

```
function loadOtherFeesExpensesInfo(){
$.getJSON(
	    "//financials.morningstar.com/oprn/c-otherFeesExpenses.action?&t=FOUSA02V1M&region=usa&culture=en-US&cur=&callback=?",
	      function(data,status) {
	      if(data.html!=""){
	    	    $("#otherFeesExpensesHtml").html(data.html);
			}
	      }
    )
}
```

Obviously that's not going to be run when you're just fetching the HTML so you need to use something like [Hound](https://github.com/HashNuke/hound) to fetch it in such a way that the script is evaluated.

At that point Meeseeks will work as expected.

**Comment by madasebrof** [comment]
Duh! Should have thought of that! Thanks for the speedy reply!

**Comment by mischov** [comment]
Glad to be of some assistance.
