### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by cjen07** [mischov/meeseeks#16]
This is a very useful library for me.

in "next" function in lib/meeseeks/selector/combinator.ex

why is there a combinator field: `struct.next(combinator, node, document)`

Thanks in advance.

**Comment by mischov** [comment]
@cjen07 
It is theoretically possible that combinator struct might contain some sort of state necessary for the logic of `next`, so it is passed in as well. The `struct` in `struct.next` is just an atom representing a module-name (not the instance of the struct itself), so to get any state from the struct it needs to be passed in.

Does that answer your question?

**Comment by cjen07** [comment]
@mischov  I got it, thanks very much!
