### ISSUE TITLE
Problem parsing simple HTML5 document

### ISSUE THREAD

**Issue by Eiji7** [mischov/meeseeks#18]
Hey, today I installed **Rust** and decided to try this library ...
Here is example HTML5 document (`index.html`):
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>Example</title>
  </head>
  <body>
    <article>
      <h1>Example header</h1>
      <p>Example paragraph ...</p>
      <footer>Example footer ...</footer>
    </article>
  </body>
</html>
```
I checked it using [W3C Markup Validation Service](https://validator.w3.org/#validate_by_input).
I entered interactive shell by `iex -S mix`.
```elixir
content = File.read!("index.html") # contents entered above
document = Meeseeks.parse(content)
import Meeseeks.CSS
elements = Meeseeks.all(document, css("*")) # I just want to check if it will fetch all elements
root_element = List.first(elements)
Meeseeks.tree(root_element)
```
Default parser results:
```elixir
{"html", [],
 [{"head", [], # missing "\n  " as first element
   ["\n    ", {"meta", [{"charset", "utf-8"}], []}, "\n    ",
    {"title", [], ["Example"]}, "\n  "]}, "\n  ",
  {"body", [],
   ["\n    ",
    {"article", [],
     ["\n      ", {"h1", [], ["Header"]}, "\n      ",
      {"main", [],
       ["\n        ", {"p", [], ["Example paragraph here ..."]}, "\n      "]},
      "\n      ", {"footer", [], ["Example footer ..."]}, "\n    "]},
    "\n  \n\n"]}]} # what ?!?!
```
I tried same code as above, but I used `:xml` parser (just set `:xml` as second argument of `parse` function like: `document = Meeseeks.parse(content, :xml)`) and here are results of it:
```elixir
{"html", [],
 ["\n  ", # Exactly! It was missed in :html parser
  {"head", [],
   ["\n    ", {"meta", [{"charset", "utf-8"}], []}, "\n    ",
    {"title", [], ["Example"]}, "\n  "]}, "\n  ",
  {"body", [],
   ["\n    ",
    {"article", [],
     ["\n      ", {"h1", [], ["Header"]}, "\n      ",
      {"main", [],
       ["\n        ", {"p", [], ["Example paragraph here ..."]}, "\n      "]},
      "\n      ", {"footer", [], ["Example footer ..."]}, "\n    "]}, "\n  "]},
  "\n"]} # Also perfect!
```

I'm using:

1. [asdf](https://github.com/asdf-vm/asdf) as version manager
2. [asdf-erlang](https://github.com/asdf-vm/asdf-erlang) (global version set to: `20.0`)
3. [asdf-elixir](https://github.com/asdf-vm/asdf-elixir) (global version set to: `ref-v1.5.0-rc.0` - compiled release candidate from source)
4. [asdf-rust](https://github.com/code-lever/asdf-rust) (global version set to: `stable`).

```bash
> rustc --version
rustc 1.17.0 (56124baa9 2017-04-24)
> elixir -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.0-rc.0 (d3a66d7)
> mix deps
* rustler 0.10.1 (Hex package) (mix)
  locked at 0.10.1 (rustler) cedcce8b
  ok
* meeseeks_html5ever 0.6.1 (Hex package) (mix)
  locked at 0.6.1 (meeseeks_html5ever) 3d7f3c4b
  ok
* meeseeks 0.7.1 (Hex package) (mix)
  locked at 0.7.1 (meeseeks) 4b42e41a
  ok
```

Of course in this example it's not a big problem, but I worry about much more complicated documents.
Can you look at it?

**Comment by mischov** [comment]
@Eiji7 

Reasonable question- the short answer is "HTML5! (probably)", but let me expand on that a little bit.

1. Reproducing your example, I see the same behavior as you.
2. Additionally, when parsing your HTML using Floki with the Html5ever parser, the result is:

    ```elixir
    iex> Floki.parse(html)
    [{:doctype, "html", "", ""},
     {"html", [],
      [{"head", [],
        ["\n    ", {"meta", [{"charset", "utf-8"}], []}, "\n    ",
         {"title", [], ["Example"]}, "\n  "]}, "\n  ",
       {"body", [],
        ["\n    ",
         {"article", [],
          ["\n      ", {"h1", [], ["Example header"]}, "\n      ",
           {"p", [], ["Example paragraph ..."]}, "\n      ",
           {"footer", [], ["Example footer ..."]}, "\n    "]}, "\n  \n\n"]}]}]
    ```
    Note the lack of newline between html and head, and the single string of newlines at the end of the document. This suggests to me that the reason the document is parsing like this is because the Rust html5ever library is parsing it like this.

3. Digging into the HTML5 parsing spec, one can see that a newline after `<html>` and before `<head>` is ignored, so omitting that newline seems to be the correct behavior. https://dev.w3.org/html5/spec-preview/tokenization.html#the-before-head-insertion-mode

4. I do not know what is going on with the newlines at the end, but I usually give the html5ever people the benefit of the doubt when it comes to correctly parsing HTML5. It could be a bug, but is probably just an arcane corner of the spec I'm not familiar with.

**Comment by Eiji7** [comment]
> @mischov
Digging into the HTML5 parsing spec, one can see that a newline after <html> and before <head> is ignored, so omitting that newline seems to be the correct behavior.

Good to know. As long as it's expected it's ok. Thanks for explanation and let me know when you will have more info about newlines at end.

**Comment by mischov** [comment]
@Eiji7 
Well, without looking too closely, the behavior seems to be associated with how newlines are processed after the `</body>`, which is by acting as if they were part of the body (and so adding them to the body, which in this case means appending them to the last text node).

https://dev.w3.org/html5/spec-preview/tokenization.html#parsing-main-afterbody

Again, it looks to be the absolutely correct HTML5 behavior.

**Comment by Eiji7** [comment]
@mischov: wow, this is really unintuitive
Anyway thanks for explanation - now I understand how it work.
