### ISSUE TITLE
Incorrectly parsing doctypes

### ISSUE THREAD

**Issue by mischov** [mischov/meeseeks#20]
As discovered in #19, there is currently a problem parsing doctypes because meeseeks_html5ever parses doctypes with a `:name` key while `Document.Doctype` expects a `:type` key (tuple tree parsing in `Meeseeks.Parser` parses correctly).

### Solution

Either parse doctypes in meeseeks_html5ever with a `:type` key, or change the `:type` key in `Node.Doctype` to being `:name`. I prefer the latter.

**Comment by mischov** [comment]
@cjen07 As of 3112c46  the following should work fine.
```elixir
b = get(url).body
document = Meeseeks.parse(b)
nodes = [document.nodes[1], document.nodes[2]]
Enum.map(nodes, &Meeseeks.Document.Node.tree(&1, document))
```

**Comment by cjen07** [comment]
Awesome, it works!
