### ISSUE TITLE
Selection using multiple selectors with filters may cause errors

### ISSUE THREAD

**Issue by mischov** [mischov/meeseeks#44]
This is another error reported by @anulman, the gist of which is that while individually the XPath selectors `/*[@itemscope]` and `//*[@itemscope][not(ancestor::*[@itemscope][1])]` work fine, 
`/*[@itemscope]|//*[@itemscope][not(ancestor::*[@itemscope][1])]`, an XPath selector combining the two of them, doesn't.

#### Problem

In short, an "optimization" in the code handling node matches during selection indirectly led to the possibility of matches stored for filtering in the context being prematurely cleared.

#### Solution

Remove the problematic optimization (which as far as I can tell generally provided very little benefit).

**Comment by mischov** [comment]
@anulman The problem should be fixed in master as of be03003. If you could test it out I would appreciate it.

I'll leave this issue open until I release a version with the fix.

**Comment by anulman** [comment]
Confirming this is resolved. Opening a new issue for the `.//` sub-selection we discussed

**Comment by mischov** [comment]
Fixed in v0.9.5.
