### ISSUE TITLE
Meeseeks.parse/1 surprising behavior with ok-tuples

### ISSUE THREAD

**Issue by axelson** [mischov/meeseeks#55]
I would expect an error to happen in the following situation:
```
iex> Meeseeks.parse({:ok, "<html></html>"})
```

Instead this is treated as a tuple tree, which makes sense but was surprising (I ran into this and wasted some time because I'm testing with file content from `File.read` and I forgot to unwrap the ok-tuple).

**Comment by mischov** [comment]
I think that probably counts as an overlooked error.

I don't think an `{:ok, _}` tuple has any valid interpretation, so at the very least it should be a parse error. I am curious why I chose to return an empty document instead, but I will investigate and add an error if there wasn't a reason.

That is the "non-breaking" solution.

The "breaking" solution is that I'm kinda regretting being "helpful" and accepting either a string or a tuple tree. A more explicit solution like `Meeseeks.parse(_, :tuple_tree)` wouldn't add much verbosity while making things a lot less surprising on the whole.

I could add that functionality without making a breaking change and slate `parse/1` with a tuple tree for deprecation, but I'd need to think about it more before making a decision one way or the other.

**Comment by axelson** [comment]
Yeah, I would generally think that you generally wouldn't call `parse` with a tuple tree since it's more likely that you're feeding raw html to Meeseeks. Generally I'm in favor of "non-breaking" solutions, but you could deprecate the tuple tree input with `parse/1` and log a warning when it is used (perhaps to be removed completely in 1.0). I'm not sure if `Meeseeks.parse(tree, :tuple_tree)` makes sense because `.parse/2` already exists and the second argument is documented to be of type `Meeseeks.Parser.type` which is defined as `:html | :xml`. Maybe adding `parse_tuple_tree/1` would make more sense? Anyway, I'm just giving my 2 cents as a very new user of the project (which has been wonderful so far!)

**Comment by mischov** [comment]
I'd assume that `Parser.type` would become `:html | :xml | :tuple_tree` in that scenario.

**Comment by axelson** [comment]
k, that makes sense

**Comment by mischov** [comment]
Fixed in `v0.11.1`.

**Comment by axelson** [comment]
Great, thanks!
